branches:
  only:
    - master
    - dev
os:
  - linux
language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
install:
  - npm install

script:
  - if [[ ${BUNDLE_ANALYZER_TOKEN} != "" ]]; then npm install --no-save @bundle-analyzer/webpack-plugin; fi
  - npm run build
  - npm test

before_deploy:
  - export TRAVIS_TAG=$(node -p "require('./package.json').version")
  - echo ${TRAVIS_TAG}
  - 'if [[ ${TAGGED} != 1 ]]; then export PACKAGE=$(npm pack --silent) && git tag ${TRAVIS_TAG} && export TAGGED=1; fi'
deploy:
  - provider: releases
    skip_cleanup: true
    file: $PACKAGE
    api_key:
      secure: iXcRgSgyD4aqe9jAGFxKlXworkDNummooQ9n+6KFLXeafsZRvx7wezPSxjtEuVLWVlbdZrkbvzq6zQRlN2OV9M1ONRCtmZvh9HvrEL3bDqWpUbM2Pk7iSSyjXQZzZll+3pSizgcELPF/WVSADPwkXd9qLWeU1pTRyYeckRuti1gQUxOxDEch3xqdycFkATEr+bDFDE9W5Z/jXpHqiouwBMLzB14o/BJzoJ7FF7c4L4dka7g+VP8UI4+CCI47qcJv09Klko4G782qRmJ7/vT+xOo/JEuDH7QJ4Su5R7IfmRiLs3LktnebYmXw0+IqAxY8hsbxnchFSx2pkS0WcRXPeIt5r9Y63wN8UVuPou57pqBVGzyw2rnKy1VEkb1QHbwvrJL8Tr5AbXKSLYlmel6xANRMOv0wRfvHlxLxKiK45NJZCgQCVNBkBKh/f9qrU+R5ZTt1DrmMR1B5O3O7hSkxCJBHXNSpTPr0Kkg6BJSYdjju+9KS/6vxvHc3n9y4mpv8iHlocqDFDgPVml1+CqNRWZ2tj/mA1GdLd1xmvjq+pdNdE6bgXlKhUqhS9/TSO1qwFYyYorQ7cVjrFDoHNM5zt9HDH7B+kv1Rhq8CU+v2PKXLMlkR+jKfhBO2Zfj1ous6s0fSNHK7L0+c3Kn7+nnh7TxrKTixKJZIlxrDbLXPM0k=
    on:
      repo: eidng8/xml-patch-cli
      branch: master
      condition: ${TRAVIS_EVENT_TYPE} == push
  - provider: npm
    skip_cleanup: true
    email: cheung.jackey@gmail.com
    api_key:
      secure: E0AMFEg7Ru5laIJKWYT161K9r8xidP8Bczgz369WMJf/v2ojBfHLT+3SMUU9EPNt8IgbxEacEe2zYvJceNF+jVPcLj6U8BjBdgxgNqyBRbTm5HS3KlLXGjj8ndbcqpaMC2MDiS/gp/7A55eqzmGgmfQ0EjRyrdCAtcjGtrK2a0hT17l4bu3bixHIJl6bX7h3Aw+xeSdRttiuXsg8BVrGbDvjGe65J9wqwhfj8JoUf5mA6z5XZ9YIlcdfhHFUwsz35nbTmePGAho/r3U8UyKMHCSFAWu0UsQfl1zjm3zlTKrdImNBtrAKCX9l+47lcrQiuT/AHJqcWXj18KVFYxayRu/cRvb5PUi3Ya77FW0/WysdwicLzGop6CgvpvcIIJ37hl18ltiCApjWG8AY7uNRHiwNCmwzHfPJDMj9YMVNDhtNGU/o8xlKimN9I3Pz88UBhO5IIcyzDcjuq/Rmk4qIVrPax8XgPl2NBkIKUIV3CoyikBh8xRagIcaaMw/DEHBA+qWm8XsSvEzIr3BEAwV0BJKRNyjaoF04vssaELHV5oSGRxBtYcQ7K28uHizL1Wq9PMO1Ls8J1qnMDRyD01H/fC6aGzfyf2YVpFSgJIJJZleENEWqI2s0wpeium2dhhcE2mQKxLr66OEw43CaMssb3z2gIwJsWMMas/EzPD/rdN0=
    on:
      repo: eidng8/xml-patch-cli
      branch: master
      condition: ${TRAVIS_EVENT_TYPE} == push
